<?php


/**
 * This class adds structure of 'country' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/26/09 11:06:06
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfIpGeolocHelperPlugin.lib.model.map
 */
class countryMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfIpGeolocHelperPlugin.lib.model.map.countryMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(countryPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(countryPeer::TABLE_NAME);
		$tMap->setPhpName('country');
		$tMap->setClassname('country');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('ISO', 'Iso', 'VARCHAR', true, 2);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 80);

		$tMap->addColumn('PRINTABLE_NAME', 'PrintableName', 'VARCHAR', true, 80);

		$tMap->addColumn('ISO3', 'Iso3', 'VARCHAR', false, 3);

		$tMap->addColumn('NUMCODE', 'Numcode', 'INTEGER', false, null);

	} // doBuild()

} // countryMapBuilder
