<?php


/**
 * This class adds structure of 'ip2country' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 04/15/09 12:27:10
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfIpGeolocHelperPlugin.lib.model.map
 */
class ip2countryMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfIpGeolocHelperPlugin.lib.model.map.ip2countryMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ip2countryPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ip2countryPeer::TABLE_NAME);
		$tMap->setPhpName('ip2country');
		$tMap->setClassname('ip2country');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('IP_FROM', 'IpFrom', 'INTEGER', true, 20);

		$tMap->addColumn('IP_TO', 'IpTo', 'INTEGER', false, 20);

		$tMap->addColumn('COUNTRY_CODE2', 'CountryCode2', 'VARCHAR', true, 2);

		$tMap->addColumn('COUNTRY_CODE3', 'CountryCode3', 'VARCHAR', true, 2);

		$tMap->addColumn('COUNTRY_NAME', 'CountryName', 'VARCHAR', true, 50);

	} // doBuild()

} // ip2countryMapBuilder
